export const APPDEPLOYURL = "http://localhost:3000"
export const APPURL = "http://localhost:8000"
export const LOGINURL = APPURL+"/login"
export const DISCOVERURL = APPURL+"/discover"
export const STREAMURL = APPURL+"/stream"
export const BLUEPRINT_URL = APPURL+"/blueprint"
export const BLUEPRINTNET_NETWORK_CREATE_URL = APPURL+"/blueprint/network/create"
export const BLUEPRINTNET_NETWORK_GET_URL = APPURL+"/blueprint/network/get"
export const BLUEPRINTNET_SUBNET_POST_URL = APPURL+"/blueprint/subnet/create"
export const BLUEPRINTNET_SUBNET_GET_URL = APPURL+"/blueprint/subnet/get"
export const BLUEPRINTNET_HOST_GET_URL = APPURL+"/blueprint/hosts/get"
export const BLUEPRINTNET_BUILD_POST_URL = APPURL+"/blueprint/hosts/build"
export const LOGIN = APPURL + "/login"
export const SIGNUP = APPURL + "/signup"
export const GETPROJECTS = APPURL + "/project/get?name=all"
export const LOCATIONPOST = APPURL + "/locations/get"
