export const APPDEPLOYURL = "http://localhost:3000"
export const APPURL = "http://localhost:8000"
export const LOGINURL = APPURL+"/login"
export const DISCOVERURL = APPURL+"/discover"
export const STREAMURL = APPURL+"/stream"
export const BLUEPRINT_URL = APPURL+"/blueprint"
